# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GBmWv6FE0HtCf2eYuc3RilOWV42vwY1E
"""

# Import necessary libraries
import pandas as pd

# Load dataset (Ensure you have uploaded 'listings_detailed.csv' in Colab)
file_path = "/content/listings_detailed.csv"
df = pd.read_csv(file_path)

### 1. Is Airbnb still primarily offering shared rooms?
room_type_counts = df["room_type"].value_counts()
print("1. Distribution of Room Types:\n", room_type_counts, "\n")

### 2. Are listings evenly distributed across all neighborhoods?
neighborhood_counts = df["neighbourhood_cleansed"].value_counts()
print("2. Top 10 Neighborhoods with Most Listings:\n", neighborhood_counts.head(10), "\n")

### 3. Are properties owned by individuals or multiple-property hosts?
host_listing_counts = df["host_id"].value_counts()
multiple_listings_hosts = (host_listing_counts > 1).sum()
single_listing_hosts = (host_listing_counts == 1).sum()
percentage_multiple_listings = (multiple_listings_hosts / len(host_listing_counts)) * 100

print("3. Host Ownership Distribution:")
print(f" - Hosts with a single listing: {single_listing_hosts}")
print(f" - Hosts with multiple listings: {multiple_listings_hosts}")
print(f" - Percentage of hosts with multiple listings: {percentage_multiple_listings:.2f}%\n")

### 4. Are prices inflated for tourists based on language (English vs. Spanish)?
df["price"] = df["price"].replace('[\$,]', '', regex=True).astype(float)
df["language"] = df["description"].apply(lambda x: "English" if isinstance(x, str) and "the" in x else "Spanish")
price_by_language = df.groupby("language")["price"].mean()

print("4. Average Price by Listing Language:")
print(price_by_language, "\n")

# Checking if certain districts have stronger price differences
price_diff_by_neighborhood = df.groupby(["neighbourhood_cleansed", "language"])["price"].mean().unstack()
price_diff_by_neighborhood["Difference"] = abs(price_diff_by_neighborhood["English"] - price_diff_by_neighborhood["Spanish"])
print("Top 5 Neighborhoods with the Biggest Price Differences:")
print(price_diff_by_neighborhood.sort_values(by="Difference", ascending=False).head(5), "\n")

### 5. Effect of various factors on price
price_factors = df[["price", "accommodates", "host_identity_verified", "bedrooms", "beds", "review_scores_rating"]].copy()
price_factors["host_identity_verified"] = price_factors["host_identity_verified"].map({"t": 1, "f": 0})
correlation_matrix = price_factors.corr()

print("5. Correlation of Factors with Price:")
print(correlation_matrix["price"].sort_values(ascending=False))

import matplotlib.pyplot as plt

# Pie chart for room types
plt.figure(figsize=(8, 6))
room_type_counts.plot(kind="pie", autopct='%1.1f%%', colors=["lightblue", "lightgreen", "red", "purple"])
plt.title("Distribution of Room Types")
plt.ylabel("")  # Hide y-label
plt.show()